- hosts: azurestack-build
  
  tasks:
  
    - name: Install Docker 
      apt: name=docker.io

    - service: name=docker state=restarted

    - name: Add Build User to docker Group
      command: usermod -aG docker teamjoomla09